# Generated by Django 4.0.2 on 2022-02-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(null=True)),
                ('developer', models.CharField(max_length=100)),
                ('published_by', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/placeholder.png', upload_to='images/')),
                ('highlighted', models.BooleanField(default=False)),
                ('gameplatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gameplatform')),
            ],
            options={
                'ordering': ['-highlighted', 'name'],
            },
        ),
    ]
